// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg6xBToHxWs2arF-z5FBnrYw-nTz1VrNY',
    appId: '1:952177932554:web:3e63a0c82d5a350894e2f3',
    messagingSenderId: '952177932554',
    projectId: 'aula-ifb',
    authDomain: 'aula-ifb.firebaseapp.com',
    storageBucket: 'aula-ifb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaXtZTZiXmab1_f3ZKv9ONg0MeAsuqfHk',
    appId: '1:952177932554:android:9665a058a223160394e2f3',
    messagingSenderId: '952177932554',
    projectId: 'aula-ifb',
    storageBucket: 'aula-ifb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRZF_fNSuwqDh3hJmNcEPwBampSDcRuJo',
    appId: '1:952177932554:ios:4c6c96eec49d1e6a94e2f3',
    messagingSenderId: '952177932554',
    projectId: 'aula-ifb',
    storageBucket: 'aula-ifb.appspot.com',
    iosClientId: '952177932554-fdkc89o49ga3m9ip08to327ovdkmj0ar.apps.googleusercontent.com',
    iosBundleId: 'br.com.optativa1.cursofirebase.crudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRZF_fNSuwqDh3hJmNcEPwBampSDcRuJo',
    appId: '1:952177932554:ios:4c6c96eec49d1e6a94e2f3',
    messagingSenderId: '952177932554',
    projectId: 'aula-ifb',
    storageBucket: 'aula-ifb.appspot.com',
    iosClientId: '952177932554-fdkc89o49ga3m9ip08to327ovdkmj0ar.apps.googleusercontent.com',
    iosBundleId: 'br.com.optativa1.cursofirebase.crudFirebase',
  );
}
